name: BUILD & PUSH IMAGE VECSYS EXAM (PRODUCTION)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_PUSH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/labovektor/vecsys-exam:stable
            ghcr.io/labovektor/vecsys-exam:${{ github.sha }}
